server:
  port: 8005
spring:
  application:
    name: order-complete-updater
  data:
    mongodb:
      authentication-database: admin
      database: restaurant_db
      port: 27017
      host: localhost